MtMoon_1F_Text_JoshIntro::
    .string "Did you come to explore the cave,\n"
    .string "too?\p"
    .string "This cave is a natural maze.\n"
    .string "Try not to get lost.$"

MtMoon_1F_Text_JoshDefeat::
    .string "It's so uncool.$"

MtMoon_1F_Text_JoshPostBattle::
    .string "I came all the way down here on my\n"
    .string "own. Doesn't this make me cool?$"

MtMoon_1F_Text_IrisIntro::
    .string "I'm waiting for my friends to find\l"
    .string "me here.$"

MtMoon_1F_Text_IrisDefeat::
    .string "I lost? Tell me it's a lie!$"

MtMoon_1F_Text_IrisPostBattle::
    .string "I came here because I heard there\n"
    .string "are some very rare fossils here.$"

MtMoon_1F_Text_RobbyIntro::
    .string "My friends lied to me!\p"
    .string "They said that I will find\n"
    .string "rare Bugs in this cave.$"

MtMoon_1F_Text_RobbyDefeat::
    .string "I lost. No surprise!$"

MtMoon_1F_Text_RobbyPostBattle::
    .string "No Bugs! Only ZUBATs!$"

MtMoon_1F_Text_JovanIntro::
    .string "They are some suspicious men here\n"
    .string "in the cave.\p"
    .string "They call themselves TEAM ROCKET!$"

MtMoon_1F_Text_JovanDefeat::
    .string "You defeated me! But I bet,\n"
    .string "you can't defeat those men.$"

MtMoon_1F_Text_JovanPostBattle::
    .string "I saw them!\n"
    .string "I'm sure they're upto something!$"

MtMoon_1F_Text_MiriamIntro::
    .string "Wow! It's way bigger in here than\n"
    .string "I thought!$"

MtMoon_1F_Text_MiriamDefeat::
    .string "Oh!\n"
    .string "I lost it!$"

MtMoon_1F_Text_MiriamPostBattle::
    .string "How do you get out of here?\n"
    .string "It's so big, I may get lost.$"

MtMoon_1F_Text_KentIntro::
    .string "You need to go through this cave\n"
    .string "to get to CERULEAN CITY.$"

MtMoon_1F_Text_KentDefeat::
    .string "My POKéMON won't do!$"

MtMoon_1F_Text_KentPostBattle::
    .string "These ZUBATs are so annoying!\n"
    .string "Aren't they?$"

MtMoon_1F_Text_MarcosIntro::
    .string "There are Pokemons,\n"
    .string "so I catch them!\p"
    .string "There are mountains,\n"
    .string "so I climb them!$"

MtMoon_1F_Text_MarcosDefeat::
    .string "Wow!\n"
    .string "You are tough!$"

MtMoon_1F_Text_MarcosPostBattle::
    .string "Kids like you shouldn't be\n"
    .string "wandering around here in the dark.$"

MtMoon_1F_Text_TeamRocketWasHere::
    .string "The original text is overwritten\n"
    .string "by some paint. Now it says...\p"
    .string "TEAM ROCKET WAS HERE!$"

MtMoon_1F_Text_BrockHelpsExcavateFossils::
    .string "Hi, I'm excavating for fossils here\n"
    .string "under MT. MOON.\p"
    .string "Sometimes, BROCK of PEWTER GYM\n"
    .string "lends me a hand.$"
