PalletTown_CodersHouse_MapScripts::
	.byte 0

PalletTown_CodersHouse_EventScript_PC::
	msgbox PalletTown_CodersHouse_Text_PC, MSGBOX_SIGN
	end

PalletTown_CodersHouse_EventScript_Sign1::
	msgbox PalletTown_CodersHouse_Text_Sign1, MSGBOX_SIGN
	end

PalletTown_CodersHouse_EventScript_Sign2::
	msgbox PalletTown_CodersHouse_Text_Sign2, MSGBOX_SIGN
	end

PalletTown_CodersHouse_EventScript_Sign3::
	msgbox PalletTown_CodersHouse_Text_Sign3, MSGBOX_SIGN
	end
