PalletTown_CodersHouse_Text_PC::
    .string "It's a bunch of complex code,\n"
    .string "and furthermore…\p"
    .string "It's in Java!$"

PalletTown_CodersHouse_Text_Sign1::
    .string "Searching Algorithms…\p"
    .string "Linear search works in\n"
    .string "O(n) time, while\p"
    .string "Binary search works in\n"
    .string "O(logn) time.$"

PalletTown_CodersHouse_Text_Sign2::
    .string "Sorting Algorithms…\p"
    .string "Selection Sort, Bubble Sort,\n"
    .string "and Insertion Sort,\p"
    .string "All of these work in\n"
    .string "O(n.n) time.$"

PalletTown_CodersHouse_Text_Sign3::
    .string "Sorting Algorithms…\p"
    .string "Merge Sort, Quick Sort,\n"
    .string "and Heap Sort,\p"
    .string "All of these work in\n"
    .string "O(n.logn) time.$"

