VermilionCity_PokemonFanClub_Text_DidYouComeToHearAboutMyMons::
    .string "I chair the POKéMON Fan Club!\n"
    .string "or should I say Old People's Club.\p"
    .string "Kids these days lack what it takes\n"
    .string "to be a good POKéMON Trainer!\p"
    .string "I raise more than a hundred\n"
    .string "POKéMON!\p"
    .string "That's why they also call me\n"
    .string "Mr.POKéMON\p"
    .string "Did you come visit to hear about\n"
    .string "my POKéMON adventures?$"

VermilionCity_PokemonFanClub_Text_ChairmansStory::
    .string "Good!\n"
    .string "Then listen up!\p"
    .string "Legends from renowned Trainers and\n"
    .string "Researchers piqued my curiosity,\p"
    .string "Driving me to start a journey\n"
    .string "to seek out mythical creatures.\p"
    .string "After months of tireless research\n"
    .string "and exploration.\p"
    .string "I stumbled upon a mysterious egg,\n"
    .string "deep within the heart of a forest.\p"
    .string "…Oops! Look at the time!\l"
    .string "I kept you too long!\p"
    .string "Thanks for hearing me out!\n"
    .string "I want you to have this!$"

VermilionCity_PokemonFanClub_Text_ReceivedEggFromChairman::
    .string "{PLAYER} received an MYSTERY EGG\n"
    .string "from the CHAIRMAN.$"

VermilionCity_PokemonFanClub_Text_ExplainBikeVoucher::
    .string "Take that BIKE VOUCHER to the\n"
    .string "BIKE SHOP in CERULEAN CITY.\p"
    .string "Exchange that for a BICYCLE\n"
    .string "free of charge!\p"
    .string "Don't worry, my favorite FEAROW\n"
    .string "will FLY me anywhere I need to go.\p"
    .string "So, I have no need for a BICYCLE.\p"
    .string "I hope you like cycling!$"

VermilionCity_PokemonFanClub_Text_ComeBackToHearStory::
    .string "Oh. Come back when you want to\n"
    .string "hear my story!$"

VermilionCity_PokemonFanClub_Text_DidntComeToSeeAboutMonsAgain::
    .string "Hello, {PLAYER}!\p"
    .string "Did you come see hear about my\n"
    .string "POKéMON adventures again?\p"
    .string "No?\n"
    .string "Too bad!$"

VermilionCity_PokemonFanClub_Text_MakeRoomForThis::
    .string "Make room for this!$"

VermilionCity_PokemonFanClub_Text_NotAllowedToGoIn::
    .string "You are not allowed to go in.\n"
    .string "You are just a kid!$"

VermilionCity_PokemonFanClub_Text_Quote1::
    .string "Start asking yourself the big\n"
    .string "questions:\p"
    .string "Who are you ? and\n"
    .string "What do you want ?$"

VermilionCity_PokemonFanClub_Text_Quote2::
    .string "Sometimes the bast way to solve\n"
    .string "your own problems is to\p"
    .string "help someone else.$"

VermilionCity_PokemonFanClub_Text_Quote3::
    .string "The key to Wisdom and Tea is\n"
    .string "Proper aging!$"

VermilionCity_PokemonFanClub_Text_Quote4::
    .string "The only thing better than finding\n"
    .string "something you are looking for is\p"
    .string "finding something that you are\n"
    .string "not looking for!$"

