PalletTown_School_0F_MapScripts::
	.byte 0

PalletTown_School_0F_EventScript_Kid1::
	msgbox PalletTown_School_0F_Text_Kid1, MSGBOX_NPC
	end

PalletTown_School_0F_EventScript_Kid2::
	msgbox PalletTown_School_0F_Text_Kid2, MSGBOX_NPC
	end

PalletTown_School_0F_EventScript_Kid3::
	msgbox PalletTown_School_0F_Text_Kid3, MSGBOX_NPC
	end

PalletTown_School_0F_EventScript_Kid4::
	msgbox PalletTown_School_0F_Text_Kid4, MSGBOX_NPC
	end

PalletTown_School_0F_EventScript_Kid5::
	msgbox PalletTown_School_0F_Text_Kid5, MSGBOX_NPC
	end

PalletTown_School_0F_EventScript_Kid6::
	msgbox PalletTown_School_0F_Text_Kid6, MSGBOX_NPC
	end

PalletTown_School_0F_EventScript_Kid7::
	msgbox PalletTown_School_0F_Text_Kid7, MSGBOX_NPC
	end

PalletTown_School_0F_EventScript_Kid8::
	msgbox PalletTown_School_0F_Text_Kid8, MSGBOX_NPC
	end

