PalletTown_School_0F_Text_Kid1::
    .string "The 17 different POKéMON types\n"
    .string "can further be divided as - \p"
    .string "Physical types & Special types.$"
    
PalletTown_School_0F_Text_Kid2::
    .string "Just like POKéMON, each MOVE\n"
    .string "also has an associated type.\p"
    .string "When the type of POKéMON and the\n"
    .string "MOVE matches, its power increases.$"
    
PalletTown_School_0F_Text_Kid3::
    .string "Grass, Fire, Water, Electric,\n"
    .string "Ice, Psychic, Dark, Dragon.\p"
    .string "These are the SPECIAL types.\p"
    .string "These use Sp.Atk and Sp.Def\n"
    .string "stats of a POKéMON.$"
    
PalletTown_School_0F_Text_Kid4::
    .string "Normal, Ground, Flying, Rock,\n"
    .string "Steel, Fighting, Poison, Bug,\p"
    .string "and Ghost.\n"
    .string "These are the PHYSICAL types.\p"
    .string "These use Ph.Atk and Ph.Def\n"
    .string "stats of a POKéMON.$"
    
PalletTown_School_0F_Text_Kid5::
    .string "Your POKéMON's defense stat\n"
    .string "is divided into two -\p"
    .string "Physical Defense and\n"
    .string "Special Defense.$"
    
PalletTown_School_0F_Text_Kid6::
    .string "Your POKéMON's attack stat\n"
    .string "is divided into two -\p"
    .string "Physical Attack and\n"
    .string "Special Attack.$"
    
PalletTown_School_0F_Text_Kid7::
    .string "There are total 17 different\n"
    .string "POKéMON types.\p"
    .string "Each type has some advantage or\n"
    .string "disadvantage over the other types.$"
    
PalletTown_School_0F_Text_Kid8::
    .string "Do you know the names of all\n"
    .string "17 POKéMON types?\p"
    .string "Well these are -\n"
    .string "Grass, Fire, Water, Normal,\p"
    .string "Electric, Ice, Ground, Flying,\n"
    .string "Rock, Steel, Fighting, Poison,\p"
    .string "Bug, Psychic, Ghost, Dark\n"
    .string "and Dragon.$"

