Route2_ViridianForest_NorthEntrance_Text_ManyMonsOnlyInForests::
    .string "Many POKéMON live only in forests \n"
    .string "and caves.\p"
    .string "You need to be persistent and look\n"
    .string "everywhere to get different kinds.$"

Route2_ViridianForest_NorthEntrance_Text_AboutHMs::
    .string "Some POKéMON moves can be used\n"
    .string "even outside a battle!\p"
    .string "These moves are known as HMs.\p"
    .string "Use FLASH to illuminate dark caves,\n"
    .string "Use CUT to cut down small bushes.\p"
    .string "I've heard that there exist\n"
    .string "more such HMs.$"

Route2_ViridianForest_NorthEntrance_Text_DoYouPlayMinecraft::
    .string "Do you play Minecraft?\n"
    .string "Do you watch anime?\p"
    .string "Do you write computer programs?\n"
    .string "Do you like Maths?\p"
    .string "Huh ? NO !?\p"
    .string "You are such a looser!!$"

