SSAnne_CaptainsOffice_Text_CaptainIFeelSeasick::
    .string "CAPTAIN: Ooargh…\n"
    .string "I feel hideous…\l"
    .string "Urrp! Seasick…$"

SSAnne_CaptainsOffice_Text_RubbedCaptainsBack::
    .string "{PLAYER} rubbed the CAPTAIN's back!\p"
    .string "Rub-rub…\n"
    .string "Rub-rub…$"

SSAnne_CaptainsOffice_Text_ThankYouHaveHMForCut::
    .string "CAPTAIN: Whew! Thank you!\n"
    .string "I'm feeling much better now.\p"
    .string "I'm Captain Briney! and this is\n"
    .string "my companion Peeko.\p"
    .string "What? You want to see my\n"
    .string "hidden CUT technique?\p"
    .string "I could show you my prized CUT\n"
    .string "technique if I weren't so ill…\p"
    .string "I know! You can have this!\n"
    .string "This HIDDEN MACHINE!\p"
    .string "Teach CUT to your POKéMON, and\n"
    .string "you can see it CUT anytime!$"

SSAnne_CaptainsOffice_Text_ObtainedHM01FromCaptain::
    .string "{PLAYER} obtained HM01\n"
    .string "from the CAPTAIN!$"

SSAnne_CaptainsOffice_Text_ExplainCut::
    .string "Using CUT, you can chop down\n"
    .string "small trees.\p"
    .string "Why not try it with the trees\n"
    .string "around VERMILION CITY?$"

SSAnne_CaptainsOffice_Text_SSAnneWillSetSailSoon::
    .string "CAPTAIN: …Whew!\p"
    .string "Now that I'm not sick anymore,\n"
    .string "I guess it's time.\p"
    .string "The S.S. ANNE will set sail soon!\p"
    .string "From KANTO, to JOHTO, to HOENN,\p"
    .string "Farewell, until our return to\n"
    .string "VERMILION CITY!$"

SSAnne_CaptainsOffice_Text_YuckShouldntHaveLooked::
    .string "Yuck!\n"
    .string "Shouldn't have looked!$"

SSAnne_CaptainsOffice_Text_TheBook::
    .string "The CAPTAIN's reading this!\p"
    .string "PIRATES OF THE HOENN REGION.$"

