PalletTown_RivalsHouse_Text_HiBrothersAtLab::
    .string "DAISY: Hi, {PLAYER}!\p"
    .string "{RIVAL}, is out at\n"
    .string "Grandpa's LAB.\p"
    .string "Also I heard Grandpa was looking\n"
    .string "for you. Go meet him in the lab.$"

PalletTown_RivalsHouse_Text_HeardYouBattledRival::
    .string "DAISY: {PLAYER}, I heard you had\n"
    .string "a battle against {RIVAL}.\p"
    .string "I hope he been nice with you!$"

PalletTown_RivalsHouse_Text_ErrandForGrandpaThisWillHelp::
    .string "Grandpa asked you to run an\n"
    .string "errand?\p"
    .string "He trusts you a lot.\n"
    .string "Here, this will help you.$"

PalletTown_RivalsHouse_Text_ReceivedTownMapFromDaisy::
    .string "{PLAYER} received a TOWN MAP\n"
    .string "from DAISY.$"

PalletTown_RivalsHouse_Text_DontHaveSpaceForThis::
    .string "You don't have space for this in\n"
    .string "your BAG.$"

PalletTown_RivalsHouse_Text_ExplainTownMap::
    .string "You can use the TOWN MAP to find\n"
    .string "out where you are, or check the\l"
    .string "names of places.$"

PalletTown_RivalsHouse_Text_PleaseGiveMonsRest::
    .string "DAISY: Just like people, POKéMON\n"
    .string "are living things.\p"
    .string "When they get tired, please give\n"
    .string "them a rest.\p"
    .string "I know you will treat your POKéMON\n"
    .string "with all love and care.$"

PalletTown_RivalsHouse_Text_ShelvesCrammedFullOfBooks::
    .string "The shelves are crammed full of\n"
    .string "books about grooming POKéMON.$"

PalletTown_RivalsHouse_Text_LikeMeToGroomMon::
    .string "DAISY: Hi, {PLAYER}!\n"
    .string "Good timing.\p"
    .string "I'm about to have some tea.\n"
    .string "Would you like to join me?\p"
    .string "Oh, but look.\n"
    .string "Your POKéMON are a little dirty.\p"
    .string "Would you like me to groom one?$"

PalletTown_RivalsHouse_Text_DontNeedAnyGrooming::
    .string "You don't need any grooming done?\n"
    .string "Okay, we'll just have tea.$"

PalletTown_RivalsHouse_Text_GroomWhichOne::
    .string "Which one should I groom?$"

PalletTown_RivalsHouse_Text_LookingNiceInNoTime::
    .string "DAISY: Okay, I'll get it looking\n"
    .string "nice in no time.$"

PalletTown_RivalsHouse_Text_ThereYouGoAllDone::
    .string "{FONT_NORMAL}{STR_VAR_1} looks dreamily content…\p"
    .string "{FONT_FEMALE}DAISY: There you go! All done.\n"
    .string "See? Doesn't it look nice?\p"
    .string "Giggle…\n"
    .string "It's such a cute POKéMON.$"

PalletTown_RivalsHouse_Text_CantGroomAnEgg::
    .string "Oh, sorry. I honestly can't\n"
    .string "groom an EGG.$"

PalletTown_RivalsHouse_Text_MayISeeFirstMon::
    .string "DAISY: Your POKéMON grow to love\n"
    .string "you if you raise them with love.\p"
    .string "For example, {PLAYER}, may I see\n"
    .string "your first POKéMON?$"

PalletTown_RivalsHouse_Text_MonFriendshipHighest::
    .string "Friendship Level: 255 $"

PalletTown_RivalsHouse_Text_MonFriendshipHigher::
    .string "Friendship Level: 200-254 $"

PalletTown_RivalsHouse_Text_MonFriendshipHigh::
    .string "Friendship Level: 150-199 $"

PalletTown_RivalsHouse_Text_MonFriendshipMid::
    .string "Friendship Level: 100-149 $"

PalletTown_RivalsHouse_Text_MonFriendshipLow::
    .string "Friendship Level: 50-99 $"

PalletTown_RivalsHouse_Text_MonFriendshipLower::
    .string "Friendship Level: 1-49 $"

PalletTown_RivalsHouse_Text_MonFriendshipLowest::
    .string "Freindship Level: 0 $"

PalletTown_RivalsHouse_Text_LovelyAndSweetClefairy::
    .string "“The lovely and sweet\n"
    .string "CLEFAIRY”$"

PalletTown_RivalsHouse_Text_ItsBigMapOfKanto::
    .string "It's a big map of the KANTO region.\n"
    .string "Now this would be useful!$"

