PalletTown_School_2F_MapScripts::
	.byte 0

PalletTown_School_2F_EventScript_GrassKid::
	msgbox PalletTown_School_2F_Text_GrassKid, MSGBOX_NPC
	end

PalletTown_School_2F_EventScript_FireKid::
	msgbox PalletTown_School_2F_Text_FireKid, MSGBOX_NPC
	end

PalletTown_School_2F_EventScript_WaterKid::
	msgbox PalletTown_School_2F_Text_WaterKid, MSGBOX_NPC
	end

PalletTown_School_2F_EventScript_ElectricKid::
	msgbox PalletTown_School_2F_Text_ElectricKid, MSGBOX_NPC
	end

PalletTown_School_2F_EventScript_PsychicKid::
	msgbox PalletTown_School_2F_Text_PsychicKid, MSGBOX_NPC
	end

PalletTown_School_2F_EventScript_DarkKid::
	msgbox PalletTown_School_2F_Text_DarkKid, MSGBOX_NPC
	end

PalletTown_School_2F_EventScript_IceKid::
	msgbox PalletTown_School_2F_Text_IceKid, MSGBOX_NPC
	end

PalletTown_School_2F_EventScript_DragonKid::
	msgbox PalletTown_School_2F_Text_DragonKid, MSGBOX_NPC
	end
