PalletTown_School_2F_Text_GrassKid::
    .string "Grass type POKéMON are weak\n"
    .string "against - Fire, Ice, Poison\p"
    .string "Flying and Bug type attacks.\n"
    .string "They resist - Water, Electric\p"
    .string "Grass and Ground type attacks.$"
    
PalletTown_School_2F_Text_FireKid::
    .string "Fire type POKéMON are weak\n"
    .string "against - Water, Ground and Rock\p"
    .string "type attacks.\n"
    .string "They resist - Fire, Grass, ice\p"
    .string "Bug and Steel type attacks.$"
    
PalletTown_School_2F_Text_WaterKid::
    .string "Water type POKéMON are weak\n"
    .string "against - Grass and Electric\p"
    .string "type attacks.\n"
    .string "They resist - Fire, Water, Ice\p"
    .string "and Steel type attacks.$"
    
PalletTown_School_2F_Text_ElectricKid::
    .string "Electric type POKéMON are weak\n"
    .string "against - Ground type attacks.\p"
    .string "They resist - Electric, Steel\n"
    .string "and Flying type attacks.$"
    
PalletTown_School_2F_Text_PsychicKid::
    .string "Psychic type POKéMON are weak\n"
    .string "against - Bug, Ghost amd Dark\p"
    .string "type attacks.\n"
    .string "They resist - Fighting and\p"
    .string "Psychic type attacks.$"
    
PalletTown_School_2F_Text_DarkKid::
    .string "Dark type POKéMON are weak\n"
    .string "against - Fighting and Bug\p"
    .string "type attacks.\n"
    .string "They resist - Ghost and Dark\p"
    .string "type attacks.\n"
    .string "They are immune to Psychic\p"
    .string "type attacks.$"
    
PalletTown_School_2F_Text_IceKid::
    .string "Ice type POKéMON are weak\n"
    .string "against - Fire, Fighting,\p"
    .string "Rock and Steel type attacks.\n"
    .string "They resist - Ice type attacks.$"
    
PalletTown_School_2F_Text_DragonKid::
    .string "Dragon type POKéMON are weak\n"
    .string "against - Ice and Dragon\p"
    .string "type attacks.\n"
    .string "They resist - Fire, Water,\p"
    .string "Electric and Grass type attacks.$"

