CeruleanCity_House1_Text_KurtIntro::
    .string "Hello, My name is KURT.\n"
    .string "I am a POKéBALL smith.\p"
    .string "I see you have the BoulderBadge.\n"
    .string "You must be a skilled trainer.\p"
    .string "Oh, you are from PALLET TOWN?\n"
    .string "Then you must be knowing PROF OAK.\p"
    .string "Here, have these as a gift.$"
    
CeruleanCity_House1_Text_ReceivedBikeVoucherFromChairman::
    .string "{PLAYER} received a BIKE VOUCHER\n"
    .string "from KURT.$"

CeruleanCity_House1_Text_MakeRoomForThis::
    .string "Make room for this!$"

CeruleanCity_House1_Text_ExplainBikeVoucher::
    .string "Take that BIKE VOUCHER to the\n"
    .string "BIKE SHOP in CERULEAN CITY.\p"
    .string "Exchange that for a BICYCLE\n"
    .string "free of charge!\p"
    .string "I used to ride bikes when I was\n"
    .string "young, Now its of no use for me.\p"
    .string "I hope you like cycling!\p"
    .string "Say my hello to PROF OAK.$"

CeruleanCity_House1_Text_AboutMasterBall::
    .string "You see there are different types\n"
    .string "POKéBALLs available in the market.\p"
    .string "Some balls increase the catch rate\n"
    .string "while some provide other perks\p"
    .string "As a POKéBALL smith, I dream to\n"
    .string "invent the most powerful POKéBALL.\p"
    .string "A POKéBALL that can catch any\n"
    .string "POKéMON without fail.$" 

