Secretcave_Text_WhoAreYou::
    .string "Who are you? \p"
    .string "Leave me alone! $"

Secretcave_Text_GuessANumber::
    .string "Hey You!\n"
    .string "Think of a 3-digit number.\p"
    .string "And I will try to guess it\n"
    .string "using my magical powers.\p"
    .string "Ready !?$" 

Secretcave_Text_YourOriginalNumber::
    .string "Your original number was {STR_VAR_1}.\n"
    .string "Am I not Amazing?\p"
    .string "Don't get scared, It's not Magic.\n"
    .string "It's Math!$" 

Secretcave_Text_IsOriginalNumberOdd::
    .string "Is the number you chose odd?$"

Secretcave_Text_IsThisNumberOdd::
    .string "Is this new number odd?$"

Secretcave_Text_DecreaseThisNumberBy1::
    .string "Decrease this number by 1,\n"
    .string "to make it an even number.$"

Secretcave_Text_NowHalfThisNumber::
    .string "Now, Divide this even number by 2.$"


