Text_DreamEaterTeach::
    .string "Yawn!\n"
    .string "I must have dozed off in the sun.\p"
    .string "I had this weird dream about\n"
    .string "a DROWZEE eating my dream.\p"
    .string "And…\n"
    .string "I learned how to eat dreams…\p"
    .string "Oogh, this is too spooky!\p"
    .string "Let me teach it to a POKéMON so\n"
    .string "I can forget about it!$"

Text_DreamEaterDeclined::
    .string "…Snore…$"

Text_DreamEaterWhichMon::
    .string "Which POKéMON wants to learn\n"
    .string "DREAM EATER?$"

Text_DreamEaterTaught::
    .string "…ZZZ…\n"
    .string "I…can't eat…anymore…$"

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

PewterCity_Text_DontLeaveTheTownYet::
    .string "What are you doing ?\p"
    .string "Leaving the town without\n"
    .string "challenging the GYM LEADER ?$"

PewterCity_Text_YouNeedGymBadges::
    .string "If you wanna be a POKéMON Master,\n"
    .string "You need the win the POKéMON League.\p"
    .string "And to be able to participate in\n"
    .string "that, you need 8 Gym Badges.\p"
    .string "And you get these Gym Badges by\n"
    .string "defeating the Gym Leaders.$"

PewterCity_Text_GoTakeOnBrock::
    .string "Go take on Brock!\p"
    .string "And claim your first Gym Badge.$"

PewterCity_Text_DidYouCheckOutMuseum::
    .string "Did you check out the\n"
    .string "PEWTER CITY SCIENCE MUSEUM?$"

PewterCity_Text_WerentThoseFossilsAmazing::
    .string "Weren't those fossils from MT. MOON\n"
    .string "amazing?$"

PewterCity_Text_ReallyYouHaveToGo::
    .string "Really?\n"
    .string "You absolutely have to go!$"

PewterCity_Text_OhPlayer::
    .string "Oh, {PLAYER}!$"

PewterCity_Text_AskedToDeliverThis::
    .string "I'm glad I caught up to you.\n"
    .string "I'm PROF. OAK's AIDE.\p"
    .string "I've been asked to deliver this,\n"
    .string "so here you go.$"

PewterCity_Text_ReceivedRunningShoesFromAide::
    .string "{PLAYER} received the\n"
    .string "RUNNING SHOES from the AIDE.$"

PewterCity_Text_SwitchedShoesWithRunningShoes::
    .string "{PLAYER} switched shoes with the\n"
    .string "RUNNING SHOES.$"

PewterCity_Text_ExplainRunningShoes::
    .string "Hold the B Button to run.\n"
    .string "But only where there's room to run!$"

PewterCity_Text_MustBeGoingBackToLab::
    .string "Well, I must be going back.\n"
    .string "Bye-bye!$"

PewterCity_Text_RunningShoesLetterFromMom::
    .string "There's a letter attached…\p"
    .string "Dear {PLAYER},\p"
    .string "Here is a pair of RUNNING SHOES\n"
    .string "for my beloved challenger.\p"
    .string "Remember, I'll always cheer for\n"
    .string "you! Don't ever give up!\p"
    .string "From Mom.$"

PewterCity_Text_DoYouKnowWhatImDoing::
    .string "Psssst!\n"
    .string "Do you know what I'm doing?$"

PewterCity_Text_ThatsRightItsHardWork::
    .string "That's right!\n"
    .string "It's hard work!$"

PewterCity_Text_SprayingRepelToKeepWildMonsOut::
    .string "I'm spraying REPEL to keep wild\n"
    .string "POKéMON out of my garden!\p"
    .string "If you to want to keep the\n"
    .string "wild POKéMON away, use REPELs.\p"

PewterCity_Text_ClefairyCameFromMoon::
    .string "CLEFAIRY came from the moon.\n"
    .string "That's what the rumor is.\p"
    .string "Believe me! I saw it in a\n"
    .string "YouTube video.$"

PewterCity_Text_BrockOnlySeriousTrainerHere::
    .string "There aren't many serious POKéMON\n"
    .string "TRAINERS here.\p"
    .string "They're all like BUG CATCHERS,\n"
    .string "you know, just hobbyists.\p"
    .string "But PEWTER GYM's BROCK isn't like\n"
    .string "that, not one bit.$"

PewterCity_Text_TrainerTipsEarningEXP::
    .string "TRAINER TIPS\p"
    .string "All POKéMON that appear in battle,\n"
    .string "however briefly, earn EXP Points.$"

PewterCity_Text_CallPoliceIfInfoOnThieves::
    .string "NOTICE!\p"
    .string "Thieves have been stealing POKéMON\n"
    .string "fossils from MT. MOON.\p"
    .string "Please call the PEWTER POLICE if\n"
    .string "you have any information.$"

PewterCity_Text_MuseumOfScience::
    .string "PEWTER CITY SCIENCE MUSEUM$"

PewterCity_Text_GymSign::
    .string "PEWTER CITY POKéMON GYM\n"
    .string "LEADER: BROCK\l"
    .string "The Rock-Solid POKéMON TRAINER!$"

PewterCity_Text_CitySign::
    .string "PEWTER CITY\n"
    .string "A Stone Gray City$"

