ViridianCity_School_Text_TryingToMemorizeNotes::
    .string "Whew! I'm trying to memorize all my\n"
    .string "notes.$"

ViridianCity_School_Text_TurnThePage::
    .string "Turn the page?$"

ViridianCity_School_Text_HeyDontLookAtMyNotes::
    .string "Hey!\n"
    .string "Don't look at my notes!$"

@@@@ GirlsNotebook - Pokemon Status Effects@@@@

ViridianCity_School_Text_GirlsNotebookFirstPage::
    .string "Let's check out the notebook.\p"
    .string "First page…\p"
    .string "There are 5 major STATUS\n"
    .string "problems during battles.$"

ViridianCity_School_Text_GirlsNotebookSecondPage::
    .string "Second page…\p"
    .string "SLP- A POKéMON can't attack\n"
    .string "if it's asleep.\p"
    .string "POKéMON will stay asleep even\n"
    .string "after battles.\p"
    .string "Use AWAKENING to awaken one\n"
    .string "from sleep.$"

ViridianCity_School_Text_GirlsNotebookThirdPage::
    .string "Third page…\p"
    .string "PRZ- Paralysis reduces SPEED and\n"
    .string "may prevent the POKéMON from moving.\p"
    .string "Paralysis remains after battles.\n"
    .string "Use PARLYZ HEAL for treatment.$"

ViridianCity_School_Text_GirlsNotebookFourthPage::
    .string "Fourth page…\p"
    .string "PSN- When poisoned, a POKéMON's\n"
    .string "health steadily drops.\p"
    .string "Poison lingers after battles.\n"
    .string "Use an ANTIDOTE to cure poison!$"

ViridianCity_School_Text_GirlsNotebookFifthPage::
    .string "Fifth page…\p"
    .string "BRN- A burn reduces ATK power.\n"
    .string "It also causes ongoing HP loss.\p"
    .string "A burn remains after a battle.\n"
    .string "Use BURN HEAL to cure a burn.$"

ViridianCity_School_Text_GirlsNotebookSixthPage::
    .string "Sixth page…\p"
    .string "FRZ- A frozen POKéMON becomes\n"
    .string "helplessly immobile.\p"
    .string "It stays frozen even after the\n"
    .string "battle ends.\p"
    .string "Use ICE HEAL to thaw out the\n"
    .string "suffering POKéMON.$"

@@@@ BoysNotebook - Ph/Sp SPLIT @@@@

ViridianCity_School_Text_BoysNotebookFirstPage::
    .string "Let's check out the notebook.\p"
    .string "First page…\p"
    .string "The 17 different POKéMON types\n"
    .string "can further be divided as - \p"
    .string "Physical types & Special types.$"

ViridianCity_School_Text_BoysNotebookSecondPage::
    .string "Second page…\p"
    .string "Normal, Ground, Flying, Rock,\n"
    .string "Steel, Fighting, Poison, Bug,\p"
    .string "and Ghost.\n"
    .string "These are the PHYSICAL types.\p"
    .string "These use Ph.Atk and Ph.Def\n"
    .string "stats of a POKéMON.$"

ViridianCity_School_Text_BoysNotebookThirdPage::
    .string "Third page…\p"
    .string "Grass, Fire, Water, Electric,\n"
    .string "Ice, Psychic, Dark, Dragon.\p"
    .string "These are the SPECIAL types.\p"
    .string "These use Sp.Atk and Sp.Def\n"
    .string "stats of a POKéMON.$"

ViridianCity_School_Text_BoysNotebookFourthPage::
    .string "Fourth page…\p"
    .string "Just like POKéMON, each MOVE\n"
    .string "also has an associated type.\p"
    .string "When the type of POKéMON and the\n"
    .string "MOVE matches, its power increases.$"

@@@@ Blackboard - Type Effectiveness @@@@

ViridianCity_School_Text_ReadBlackboardCarefully::
    .string "Okay!\p"
    .string "Be sure to read what's on the\n"
    .string "blackboard carefully!$"

ViridianCity_School_Text_BlackboardListsTypeEffects::
    .string "The blackboard lists POKéMON\n"
    .string "TYPE effects during battles.$"

ViridianCity_School_Text_ReadWhichTopic::
    .string "Which type do you want to study?$"

ViridianCity_School_Text_Normal::
    .string "Normal type POKéMON are weak\n"
    .string "against - Fighting type attacks.\p"
    .string "They are immune to Ghost\n"
    .string "type attacks.$"
    
ViridianCity_School_Text_Fire::
    .string "Fire type POKéMON are weak\n"
    .string "against - Water, Ground and Rock\p"
    .string "type attacks.\n"
    .string "They resist - Fire, Grass, ice\p"
    .string "Bug and Steel type attacks.$"
    
ViridianCity_School_Text_Water::
    .string "Water type POKéMON are weak\n"
    .string "against - Grass and Electric\p"
    .string "type attacks.\n"
    .string "They resist - Fire, Water, Ice\p"
    .string "and Steel type attacks.$"
    
ViridianCity_School_Text_Electric::
    .string "Electric type POKéMON are weak\n"
    .string "against - Ground type attacks.\p"
    .string "They resist - Electric, Steel\n"
    .string "and Flying type attacks.$"

ViridianCity_School_Text_Grass::
    .string "Grass type POKéMON are weak\n"
    .string "against - Fire, Ice, Poison\p"
    .string "Flying and Bug type attacks.\n"
    .string "They resist - Water, Electric\p"
    .string "Grass and Ground type attacks.$"
    
ViridianCity_School_Text_Ice::
    .string "Ice type POKéMON are weak\n"
    .string "against - Fire, Fighting,\p"
    .string "Rock and Steel type attacks.\n"
    .string "They resist - Ice type attacks.$"
    
ViridianCity_School_Text_Fighting::
    .string "Fighting type POKéMON are weak\n"
    .string "against - Flying and Psychic\p"
    .string "type attacks.\n"
    .string "They resist - Rock, Bug\p"
    .string "and Dark type attacks.$"
    
ViridianCity_School_Text_Poison::
    .string "Poison type POKéMON are weak\n"
    .string "against - Ground and\p"
    .string "Psychic type attacks.\n"
    .string "They resist - Grass, Poison,\p"
    .string "Bug and Fighting type attacks.$"

ViridianCity_School_Text_Ground::
    .string "Ground type POKéMON are weak\n"
    .string "against - Water, Grass and Ice\p"
    .string "type attacks.\n"
    .string "They resist - Poison and Rock\p"
    .string "type attacks.\n"
    .string "They are immune to Electric\p"
    .string "type attacks.$"
    
ViridianCity_School_Text_Flying::
    .string "Flying type POKéMON are weak\n"
    .string "against - Electric, Rock and\p"
    .string "Ice type attacks.\n"
    .string "They resist - Grass, Bug\p"
    .string "and Fighting type attacks.\n"
    .string "They are immune to Ground\p"
    .string "type attacks.$"
    
ViridianCity_School_Text_Psychic::
    .string "Psychic type POKéMON are weak\n"
    .string "against - Bug, Ghost amd Dark\p"
    .string "type attacks.\n"
    .string "They resist - Fighting and\p"
    .string "Psychic type attacks.$"
    
ViridianCity_School_Text_Bug::
    .string "Bug type POKéMON are weak\n"
    .string "against - Fire, Flying and\p"
    .string "Rock type attacks.\n"
    .string "They resist - Grass, Ground\p"
    .string "and Fighting type attacks.$"
    
ViridianCity_School_Text_Rock::
    .string "Rock type POKéMON are weak\n"
    .string "against - Water, Grass, Ground,\p"
    .string "Fighting and Steel type\n"
    .string "attacks\p"
    .string "They resist - Normal, Fire\n"
    .string "Poison and Flying type attacks.$"
    
ViridianCity_School_Text_Ghost::
    .string "Ghost type POKéMON are weak\n"
    .string "against - Ghost and Dark\p"
    .string "type attacks.\n"
    .string "They resist - Poison and Bug\p"
    .string "type attacks.\n"
    .string "They are immune to Normal\p"
    .string "and Fighting type attacks.$"
    
ViridianCity_School_Text_Dragon::
    .string "Dragon type POKéMON are weak\n"
    .string "against - Ice and Dragon\p"
    .string "type attacks.\n"
    .string "They resist - Fire, Water,\p"
    .string "Electric and Grass type attacks.$"
    
ViridianCity_School_Text_Dark::
    .string "Dark type POKéMON are weak\n"
    .string "against - Fighting and Bug\p"
    .string "type attacks.\n"
    .string "They resist - Ghost and Dark\p"
    .string "type attacks.\n"
    .string "They are immune to Psychic\p"
    .string "type attacks.$"
    
ViridianCity_School_Text_Steel::
    .string "Steel type POKéMON are weak\n"
    .string "against - Fire, Ground and\p"
    .string "Fighting type attacks.\n"
    .string "They resist - Normal, Ice, Bug,\p"
    .string "Grass, Flying, Psychic, Rock,\n"
    .string "Dragon and Steel type attacks.\p"
    .string "They are immune to Poison\n"
    .string "type attacks.$"

