ViridianCity_Mart_Text_YouCameFromPallet::
    .string "Hey!\n"
    .string "You came from PALLET TOWN?$"

ViridianCity_Mart_Text_TakeThisToProfOak::
    .string "You know PROF. OAK, right?\p"
    .string "His order came in.\n"
    .string "Can I get you to take it to him?$"

ViridianCity_Mart_Text_ReceivedOaksParcelFromClerk::
    .string "{PLAYER} received OAK'S PARCEL\n"
    .string "from the POKéMON MART clerk.$"

ViridianCity_Mart_Text_SayHiToOakForMe::
    .string "Okay, thanks! Please say hi to\n"
    .string "PROF. OAK for me, too.$"

ViridianCity_Mart_Text_ShopDoesGoodBusinessInAntidotes::
    .string "You must always carry some\n"
    .string "ANTIDOTES.\p"
    .string "Poisoned POKéMON loose HP\n"
    .string "even outside battle.$"

ViridianCity_Mart_Text_GotToBuySomePotions::
    .string "I've got to buy some POTIONS.\p"
    .string "You never know when your POKéMON\n"
    .string "will need quick healing.$"

