Route2_ViridianForest_SouthEntrance_Text_ForestIsMaze::
    .string "Are you going to the\n"
    .string "VIRIDIAN FOREST?\p"
    .string "Be careful and don't get lost.\n"
    .string "It's something of a maze itself.$"

Route2_ViridianForest_SouthEntrance_Text_TakeFrequentBreaks::
    .string "Which emulator do you use\n"
    .string "for playing GBA games.\p"
    .string "My Boy! Emulator is the best one.\p"
    .string "It allows you to have link battles\n"
    .string "with your friends.$"

