ViridianCity_House_Text_NicknamingIsFun::
    .string "Coming up with nicknames is fun,\n"
    .string "but it's not so easy to do.\p"
    .string "Clever names are nice, but simple\n"
    .string "names are easier to remember.$"

ViridianCity_House_Text_MyDaddyLovesMonsToo::
    .string "We nicknamed our SPEAROW.\n"
    .string "now we call him JACK.$"

ViridianCity_House_Text_Speary::
    .string "JACK: Tetweet!$"

ViridianCity_House_Text_SpearowNameSpeary::
    .string "Species Name: SPEAROW\n"
    .string "Nickname: JACK$"

