PalletTown_Text_DontGoOut::
    .string "You should not go out,\n"
    .string "without a POKéMON!$"

PalletTown_Text_GrassUnsafeNeedMon::
    .string "It's unsafe!\n"
    .string "Wild POKéMON live in tall grass!\p"
    .string "You need your own POKéMON for\n"
    .string "your protection.$"

PalletTown_Text_GoVisitOak::
    .string "Go Visit Prof. OAK!\n"
    .string "He must be back in his Lab by now.$"

PalletTown_Text_FatMan::
    .string "Technology is incredible!\p"
    .string "But sometimes, you should take\n"
    .string "some rest, and touch some grass.$"

PalletTown_Text_Boy::
    .string "I'm raising POKéMON, too.\p"
    .string "Do you know that certain POKéMON\n"
    .string "evolve and get even stronger ?$"

PalletTown_Text_Teacher::
    .string "If this is your first time\n"
    .string "playing a POKéMON game,\p"
    .string "visit the PALLET ACADEMY\n"
    .string "to learn more about POKéMON.\p"
    .string "And yes! I just broke the\n"
    .string "fourth wall! (smirks)$"

PalletTown_Text_OakPokemonResearchLab::
    .string "OAK POKéMON RESEARCH LAB$"

PalletTown_Text_PlayersHouse::
    .string "{PLAYER}'s house$"

PalletTown_Text_RivalsHouse::
    .string "{RIVAL}'s house$"

PalletTown_Text_CodersHouse::
    .string "Coder's house\n"
    .string "Git Commit, Git Push.$"

PalletTown_Text_SchoolSign::
    .string "PALLET ACADEMY\n"
    .string "Learn more about POKéMON!$"

PalletTown_Text_TownSign::
    .string "PALLET TOWN\n"
    .string "Shades of your journey await!$"

PalletTown_Text_OakLetMeSeePokedex::
    .string "OAK: Ah, {PLAYER}!\n"
    .string "You're back, are you?\p"
    .string "How much have you filled in your\n"
    .string "POKéDEX?\p"
    .string "May I see it?\p"
    .string "Let's see…$"

PalletTown_Text_CaughtXPuttingInHonestEffort::
    .string "You've caught {STR_VAR_2}…\p"
    .string "Hm, it looks as if you're putting\n"
    .string "in an honest effort.\p"
    .string "When you manage to fill it some\n"
    .string "more, come show me, please.$"

PalletTown_Text_CaughtXImpressiveFollowMe::
    .string "You've caught… {STR_VAR_2}!?\n"
    .string "Now, this is impressive!\p"
    .string "There's something I wanted to ask\n"
    .string "of you, {PLAYER}.\p"
    .string "Come.\n"
    .string "Follow me.$"

PalletTown_Text_OakYouEnjoyingTraveling::
    .string "OAK: Ah, {PLAYER}!\n"
    .string "You seem to be enjoying traveling.\p"
    .string "Knowing you, {PLAYER}, I can easily\n"
    .string "imagine you going out to even more\l"
    .string "exotic locales.\p"
    .string "Good for you, good for you.\n"
    .string "Hohoho.$"

