PalletTown_School_1F_MapScripts::
	.byte 0

PalletTown_School_1F_EventScript_GroundKid::
	msgbox PalletTown_School_1F_Text_GroundKid, MSGBOX_NPC
	end

PalletTown_School_1F_EventScript_FlyingKid::
	msgbox PalletTown_School_1F_Text_FlyingKid, MSGBOX_NPC
	end

PalletTown_School_1F_EventScript_RockKid::
	msgbox PalletTown_School_1F_Text_RockKid, MSGBOX_NPC
	end

PalletTown_School_1F_EventScript_SteelKid::
	msgbox PalletTown_School_1F_Text_SteelKid, MSGBOX_NPC
	end

PalletTown_School_1F_EventScript_FightingKid::
	msgbox PalletTown_School_1F_Text_FightingKid, MSGBOX_NPC
	end

PalletTown_School_1F_EventScript_PoisonKid::
	msgbox PalletTown_School_1F_Text_PoisonKid, MSGBOX_NPC
	end

PalletTown_School_1F_EventScript_BugKid::
	msgbox PalletTown_School_1F_Text_BugKid, MSGBOX_NPC
	end

PalletTown_School_1F_EventScript_GhostKid::
	msgbox PalletTown_School_1F_Text_GhostKid, MSGBOX_NPC
	end

PalletTown_School_1F_EventScript_NormalKid::
	msgbox PalletTown_School_1F_Text_NormalKid, MSGBOX_NPC
	end
