PalletTown_School_1F_Text_GroundKid::
    .string "Ground type POKéMON are weak\n"
    .string "against - Water, Grass and Ice\p"
    .string "type attacks.\n"
    .string "They resist - Poison and Rock\p"
    .string "type attacks.\n"
    .string "They are immune to Electric\p"
    .string "type attacks.$"
    
PalletTown_School_1F_Text_FlyingKid::
    .string "Flying type POKéMON are weak\n"
    .string "against - Electric, Rock and\p"
    .string "Ice type attacks.\n"
    .string "They resist - Grass, Bug\p"
    .string "and Fighting type attacks.\n"
    .string "They are immune to Ground\p"
    .string "type attacks.$"
    
PalletTown_School_1F_Text_RockKid::
    .string "Rock type POKéMON are weak\n"
    .string "against - Water, Grass, Ground,\p"
    .string "Fighting and Steel type\n"
    .string "attacks\p"
    .string "They resist - Normal, Fire\n"
    .string "Poison and Flying type attacks.$"
    
PalletTown_School_1F_Text_SteelKid::
    .string "Steel type POKéMON are weak\n"
    .string "against - Fire, Ground and\p"
    .string "Fighting type attacks.\n"
    .string "They resist - Normal, Ice, Bug,\p"
    .string "Grass, Flying, Psychic, Rock,\n"
    .string "Dragon and Steel type attacks.\p"
    .string "They are immune to Poison\n"
    .string "type attacks.$"
    
PalletTown_School_1F_Text_FightingKid::
    .string "Fighting type POKéMON are weak\n"
    .string "against - Flying and Psychic\p"
    .string "type attacks.\n"
    .string "They resist - Rock, Bug\p"
    .string "and Dark type attacks.$"
    
PalletTown_School_1F_Text_PoisonKid::
    .string "Poison type POKéMON are weak\n"
    .string "against - Ground and\p"
    .string "Psychic type attacks.\n"
    .string "They resist - Grass, Poison,\p"
    .string "Bug and Fighting type attacks.$"
    
PalletTown_School_1F_Text_BugKid::
    .string "Bug type POKéMON are weak\n"
    .string "against - Fire, Flying and\p"
    .string "Rock type attacks.\n"
    .string "They resist - Grass, Ground\p"
    .string "and Fighting type attacks.$"
    
PalletTown_School_1F_Text_GhostKid::
    .string "Ghost type POKéMON are weak\n"
    .string "against - Ghost and Dark\p"
    .string "type attacks.\n"
    .string "They resist - Poison and Bug\p"
    .string "type attacks.\n"
    .string "They are immune to Normal\p"
    .string "and Fighting type attacks.$"
    
PalletTown_School_1F_Text_NormalKid::
    .string "Normal type POKéMON are weak\n"
    .string "against - Fighting type attacks.\p"
    .string "They are immune to Ghost\n"
    .string "type attacks.$"

